### ISSUE TITLE
Issue with multiple Printers and not having a default

### ISSUE THREAD

**Issue by mpx1986** [KlipperScreen/KlipperScreen#1093]
### What happened?

After the last update the printer selection doesn't show

### What did you expect to happen instead?

Select printer option/dialog

### How to reproduce this bug?

Open Klipperscreen with multiple printers and without a default printer configured

### Log output

```shell
--------------------KlipperScreen Log Start--------------------
Git Version: v0.3.4-45-g2b7ad19
2023-08-21 10:39:45,936 [screen.py:main()] - Python version: 3.10
2023-08-21 10:39:45,936 [screen.py:main()] - KlipperScreen version: v0.3.4-45-g2b7ad19
2023-08-21 10:39:45,940 [screen.py:__init__()] - Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 97, in __init__
    super().__init__(title="KlipperScreen")
  File "/home/pi/.KlipperScreen-env/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
2023-08-21 10:39:45,941 [screen.py:main()] - Failed to initialize window
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 97, in __init__
    super().__init__(title="KlipperScreen")
  File "/home/pi/.KlipperScreen-env/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 1048, in main
    win = KlipperScreen(args, version)
  File "/home/pi/KlipperScreen/screen.py", line 100, in __init__
    raise RuntimeError from e
RuntimeError
2023-08-21 10:39:45,941 [screen.py:<module>()] - Fatal error in main loop:
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 97, in __init__
    super().__init__(title="KlipperScreen")
  File "/home/pi/.KlipperScreen-env/lib/python3.10/site-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 1048, in main
    win = KlipperScreen(args, version)
  File "/home/pi/KlipperScreen/screen.py", line 100, in __init__
    raise RuntimeError from e
RuntimeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 1059, in <module>
    main()
  File "/home/pi/KlipperScreen/screen.py", line 1051, in main
    raise RuntimeError from e
RuntimeError

```

**Comment by mpx1986** [comment]
Please make a option to deactivate the default printer

**Comment by alfrix** [comment]
the bug report form exists for a reason never copy paste everything like this, explain yourself.
the form guides you, the only reason why i don't close this, it's because someone else have described the issue in discord

**Comment by alfrix** [comment]
fixed the bug report, try to follow the form next time
