### ISSUE TITLE
[BUG] Spoolman page crashes on load if you have a filament type with no material set

### ISSUE THREAD

**Issue by TomW1605** [KlipperScreen/KlipperScreen#1132]
### What happened?

if you have a spool in spoolman who's filament doesn't have a material it will crash when it tries to make the list of materials

### What did you expect to happen instead?

load the screen

### How to reproduce this bug?

add a filament and dont fill in the material section, then add a spool that uses that filament, then try and load the spoolman screen on klipperscreen

### Log output

```shell
i added some debug output to check that it was loading some spools then crashing (just printing out the filament object)


2023-09-30 23:29:55,819 [screen.py:_load_panel()] - Loading panel: spoolman
2023-09-30 23:29:55,965 [KlippyRest.py:_do_request()] - Sending request to http://127.0.0.1:7125/server/spoolman/proxy
2023-09-30 23:29:55,984 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x6980de80>
2023-09-30 23:29:55,987 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81460>
2023-09-30 23:29:55,989 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81a30>
2023-09-30 23:29:55,992 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81940>
2023-09-30 23:29:55,994 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f818b0>
2023-09-30 23:29:55,996 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81100>
2023-09-30 23:29:55,999 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81748>
2023-09-30 23:29:56,001 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f816d0>
2023-09-30 23:29:56,004 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81118>
2023-09-30 23:29:56,007 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f817f0>
2023-09-30 23:29:56,009 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81778>
2023-09-30 23:29:56,011 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81700>
2023-09-30 23:29:56,013 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81838>
2023-09-30 23:29:56,015 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x6980db98>
2023-09-30 23:29:56,018 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81628>
2023-09-30 23:29:56,020 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f819d0>
2023-09-30 23:29:56,023 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81988>
2023-09-30 23:29:56,025 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x6980dca0>
2023-09-30 23:29:56,028 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x6980dc28>
2023-09-30 23:29:56,029 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81268>
2023-09-30 23:29:56,032 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68dd7268>
2023-09-30 23:29:56,034 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81688>
2023-09-30 23:29:56,037 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68f81ac0>
2023-09-30 23:29:56,040 [spoolman.py:load_spools()] - <panels.spoolman.SpoolmanFilament object at 0x68dd70d0>
2023-09-30 23:29:56,046 [screen.py:show_error_modal()] - Showing error modal: Unable to load panel spoolman 'SpoolmanFilament' object has no attribute 'material'

Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 289, in show_panel
    self.panels[panel_name] = self._load_panel(panel).Panel(self, title, **kwargs)
  File "/home/pi/KlipperScreen/panels/spoolman.py", line 250, in __init__
    self.load_spools()
  File "/home/pi/KlipperScreen/panels/spoolman.py", line 400, in load_spools
    if spoolObject.filament.material not in materials:
AttributeError: 'SpoolmanFilament' object has no attribute 'material'

2023-09-30 23:29:56,123 [KlippyGtk.py:Dialog()] - Showing dialog Error (width=480, height=800)
--------------------KlipperScreen Log Start--------------------
```
```

**Comment by TomW1605** [comment]
> Hi , I have the same problem. Did you find a solution ? thk

this was fixed at the time. that fix is still in the code so should still be working but i havnt updated klipper screen in ages so i dont know. might be worth checking what version you are on and making sure its not just really out of date
