### ISSUE TITLE
Klipper updated and now KlipperScreen is Borked[BUG] <title>

### ISSUE THREAD

**Issue by hURdERP** [KlipperScreen/KlipperScreen#1221]
### What happened?

After updating today, KlipperScreen has stopped functioning. I got it to display at least, but fuctionality of my TFT50 is nonexistent. Why would an update cause this functionality to stop and why do I have to spend time fixing an update? The config file is the culprit, and now I can find a replacement config file. Help?

### What did you expect to happen instead?

The application to update without destroying functionality

### How to reproduce this bug?

Update Klipper

### Log output

```shell
2023-12-31 10:33:07,482 [functions.py:log_start()] - --------------------KlipperScreen Log Start--------------------
2023-12-31 10:33:07,483 [functions.py:log_start()] - KlipperScreen Version: v0.3.8-7-g906831a
2023-12-31 10:33:07,483 [functions.py:log_start()] - Python version: 3.9
2023-12-31 10:33:07,642 [config.py:get_config_file_location()] - Passed config (-c): /home/pi/KlipperScreen.conf
2023-12-31 10:33:07,643 [config.py:__init__()] - Config path location: /home/pi/klipper_config/KlipperScreen.conf
2023-12-31 10:33:07,656 [config.py:__init__()] - Unknown error with the config:
Source contains parsing errors: '<string>'
	[line 40]: 'printer.bltouch # Available if bltouch section defined in config\n'
	[line 41]: 'printer.gcode_macros.count # Number of gcode macros\n'
	[line 42]: 'printer.idle_timeout # Idle timeout section\n'
	[line 43]: 'printer.pause_resume # Pause resume section of Klipper\n'
	[line 44]: 'printer.probe # Available if probe section defined in config\n'
	[line 45]: 'printer.power_devices.count # Number of power devices configured in Moonraker\n'
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/ks_includes/config.py", line 55, in __init__
    self.defined_config.read_string(user_def)
  File "/usr/lib/python3.9/configparser.py", line 723, in read_string
    self.read_file(sfile, source)
  File "/usr/lib/python3.9/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.9/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '<string>'
	[line 40]: 'printer.bltouch # Available if bltouch section defined in config\n'
	[line 41]: 'printer.gcode_macros.count # Number of gcode macros\n'
	[line 42]: 'printer.idle_timeout # Idle timeout section\n'
	[line 43]: 'printer.pause_resume # Pause resume section of Klipper\n'
	[line 44]: 'printer.probe # Available if probe section defined in config\n'
	[line 45]: 'printer.power_devices.count # Number of power devices configured in Moonraker\n'
```

**Comment by alfrix** [comment]
it's clear from your log that you have copied and pasted from the docs without reading the docs
do yourself a favor and delete the config file, as the documantation says

> It is strongly recommended that you do not add settings to the config file if you don't need them
