### ISSUE TITLE
[BUG] Unable to load panel zcalibrate on delta printer due to missing "mesh_min"

### ISSUE THREAD

**Issue by StarkRG** [KlipperScreen/KlipperScreen#1310]
### What happened?

When tapping on the zcalibrate button to load its panel the following error is displayed:

`'mesh_min'

Traceback (most recent call last):
  File "/home/starkrg/KlipperScreen/screen.py", line 321, in show_panel
    self.panels[panel_name] = self._load_panel(panel).Panel(self, title, **kwargs)
  File "/home/starkrg/KlipperScreen/panels/zcalibrate.py", line 60, in __init__
    self.set_functions()
  File "/home/starkrg/KlipperScreen/panels/zcalibrate.py", line 108, in set_functions
    self.mesh_min = self._csv_to_array(self._printer.get_config_section("bed_mesh")['mesh_min'])
KeyError: 'mesh_min'`

### What did you expect to happen instead?

According to the klipper documentation "mesh_min" is only required for rectangular beds so the panel shouldn't be looking for it. The "mesh_radius" parameter is probably what it should be looking for instead when the printer is a delta.

### How to reproduce this bug?

On a delta printer which should not have a "mesh_min" parameter set, select the zcalibrate panel.

### Log output

```shell
Log will be in next comment since this form won't accept file attachments.
```

**Comment by StarkRG** [comment]
[KlipperScreen.log](https://github.com/KlipperScreen/KlipperScreen/files/14694221/KlipperScreen.log)
