### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'sdbus'

### ISSUE THREAD

**Issue by gasparirob** [KlipperScreen/KlipperScreen#1493]
### What happened?

I have a FLSUN V400 with Klipper installed. When I click on the "Network" button I obtain the error in object (and thus I cannot change Wifi settings)

### What did you expect to happen instead?

I expect to setup printer Wifi

### How to reproduce this bug?

Press "Network" button (inside Configuration)

### Log output

I suppose this is the needed part:

024-10-27 14:25:07,542 [screen.py:_load_panel()] - Loading panel: network
2024-10-27 14:25:07,571 [screen.py:show_error_modal()] - Showing error modal: Unable to load panel network No module named 'sdbus'

Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 330, in show_panel
    self.panels[panel_name] = self._load_panel(panel).Panel(self, title, **kwargs)
  File "/home/pi/KlipperScreen/screen.py", line 312, in _load_panel
    return import_module(f"panels.{panel}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/KlipperScreen/panels/network.py", line 9, in <module>
    from ks_includes.sdbus_nm import SdbusNm
  File "/home/pi/KlipperScreen/ks_includes/sdbus_nm.py", line 7, in <module>
    import sdbus
ModuleNotFoundError: No module named 'sdbus'

2024-10-27 14:25:07,815 [KlippyGtk.py:Dialog()] - Showing dialog Error (width=1024, height=600)

But I have also attached the full log.
[KlipperScreen.log](https://github.com/user-attachments/files/17534308/KlipperScreen.log)

**Comment by alfrix** [comment]
The install of the dependencies is handled by the installer or moonraker if it's an update, if it wasn't installed, the installer would have failed with an error, the way to fix this would be to re-run the installer, BUT since you are not using this repository but a [fork](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad), i don't know for sure if that is applicable to you, so i have to close the issue since it's not valid for this repo, you should consult with the maintainer of that [fork](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad)
